# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from maestro/MaestroOut.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MaestroOut(genpy.Message):
  _md5sum = "bb3af52bc1b2d97529b338a827a298a4"
  _type = "maestro/MaestroOut"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 error
uint16 drive_position
uint16 steering_position
float64 currTime
"""
  __slots__ = ['error','drive_position','steering_position','currTime']
  _slot_types = ['int32','uint16','uint16','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       error,drive_position,steering_position,currTime

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MaestroOut, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.error is None:
        self.error = 0
      if self.drive_position is None:
        self.drive_position = 0
      if self.steering_position is None:
        self.steering_position = 0
      if self.currTime is None:
        self.currTime = 0.
    else:
      self.error = 0
      self.drive_position = 0
      self.steering_position = 0
      self.currTime = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i2Hd().pack(_x.error, _x.drive_position, _x.steering_position, _x.currTime))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.error, _x.drive_position, _x.steering_position, _x.currTime,) = _get_struct_i2Hd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i2Hd().pack(_x.error, _x.drive_position, _x.steering_position, _x.currTime))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.error, _x.drive_position, _x.steering_position, _x.currTime,) = _get_struct_i2Hd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i2Hd = None
def _get_struct_i2Hd():
    global _struct_i2Hd
    if _struct_i2Hd is None:
        _struct_i2Hd = struct.Struct("<i2Hd")
    return _struct_i2Hd
