// Generated by gencpp from file utm_laser/Laser.msg
// DO NOT EDIT!


#ifndef UTM_LASER_MESSAGE_LASER_H
#define UTM_LASER_MESSAGE_LASER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace utm_laser
{
template <class ContainerAllocator>
struct Laser_
{
  typedef Laser_<ContainerAllocator> Type;

  Laser_()
    : header()
    , Target_Easting(0.0)
    , Target_Northing(0.0)  {
    }
  Laser_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Target_Easting(0.0)
    , Target_Northing(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _Target_Easting_type;
  _Target_Easting_type Target_Easting;

   typedef double _Target_Northing_type;
  _Target_Northing_type Target_Northing;





  typedef boost::shared_ptr< ::utm_laser::Laser_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utm_laser::Laser_<ContainerAllocator> const> ConstPtr;

}; // struct Laser_

typedef ::utm_laser::Laser_<std::allocator<void> > Laser;

typedef boost::shared_ptr< ::utm_laser::Laser > LaserPtr;
typedef boost::shared_ptr< ::utm_laser::Laser const> LaserConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utm_laser::Laser_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utm_laser::Laser_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace utm_laser

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'utm_laser': ['/home/nuccar/roscar_2018/src/roscar/utm_laser/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::utm_laser::Laser_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utm_laser::Laser_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utm_laser::Laser_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utm_laser::Laser_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utm_laser::Laser_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utm_laser::Laser_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utm_laser::Laser_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d3ef403ce43b03eb3ad99eeb89714ea8";
  }

  static const char* value(const ::utm_laser::Laser_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd3ef403ce43b03ebULL;
  static const uint64_t static_value2 = 0x3ad99eeb89714ea8ULL;
};

template<class ContainerAllocator>
struct DataType< ::utm_laser::Laser_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utm_laser/Laser";
  }

  static const char* value(const ::utm_laser::Laser_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utm_laser::Laser_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 Target_Easting\n\
float64 Target_Northing\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::utm_laser::Laser_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utm_laser::Laser_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Target_Easting);
      stream.next(m.Target_Northing);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Laser_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utm_laser::Laser_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utm_laser::Laser_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Target_Easting: ";
    Printer<double>::stream(s, indent + "  ", v.Target_Easting);
    s << indent << "Target_Northing: ";
    Printer<double>::stream(s, indent + "  ", v.Target_Northing);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTM_LASER_MESSAGE_LASER_H
