global_costmap:
  global_frame: /odom
  robot_base_frame: base_link
  static_map: false
  rolling_window: true
  width: 20.0
  height: 20.0
  resolution: 0.05
  update_frequency: 1.0
  publish_frequency: 0.5


