local_costmap:
  global_frame: /odom
  robot_base_frame: base_link
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05
  update_frequency: 1.0
  publish_frequency: 5.0
  plugins:
    - {name: voxel_layer, type: "costmap_2d::VoxelLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  voxel_layer:
   map_type: voxel
   enabled: true
   width: 10
   height: 10
   rolling_window: true
   origin_z: 0.0
   z_resolution: 0.05
   z_voxels: 10
   min_obstacle_height: 0.0
   max_obstacle_height: 50.0
   obstacle_range: 0.8
   raytrace_range: 0.8
   unknown_threshold: 0
   publish_voxel_map: true
   observation_sources: voxel_pc_sensor

   voxel_pc_sensor: 
    data_type: PointCloud2
    topic: /camera/depth_registered/points
    marking: true
    clearing: true

  obstacle_layer:
   width: 10
   height: 10  
   rolling_window: true
   origin_z: 0.0
   z_resolution: 0.2
   min_obstacle_height: 0.25
   max_obstacle_height: 50.0
   marking: true
   clearing: true
   observation_sources: obstacle_pc_sensor

   obstacle_pc_sensor: 
    data_type: PointCloud2
    topic: /camera/depth_registered/points
    marking: true
    clearing: true

  inflation_layer:
   inflation_radius: 0.1
   rolling_window: true
   z_resolution: 0.2
   origin_z: 0.0
   min_obstacle_height: 0.25
   marking: true
   clearing: true
   observation_sources: inflation_pc_sensor

   inflation_pc_sensor: 
    data_type: PointCloud2
    topic: /camera/depth_registered/points
    marking: true
    clearing: true

