update_frequency: 2.0
publish_frequency: 1.0
rolling_window: true
static_map: false
footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]
plugins: 
    - {name: voxel_layer, type: "costmap_2d::VoxelLayer"}

voxel_layer: 
 enabled: true
 origin_z: 0.0
 z_resolution: 0.05
 z_voxels: 10
 unknown_threshold: 0
 publish_voxel_map: true
 observation_sources: pc

 pc: {data_type: PointCloud2, topic: /camera/depth_registered/points, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 5.0}





