// Generated by gencpp from file phidget_gps/Data.msg
// DO NOT EDIT!


#ifndef PHIDGET_GPS_MESSAGE_DATA_H
#define PHIDGET_GPS_MESSAGE_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace phidget_gps
{
template <class ContainerAllocator>
struct Data_
{
  typedef Data_<ContainerAllocator> Type;

  Data_()
    : header()
    , fix_status(false)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , is_velocity_valid(false)
    , velocity(0.0)
    , is_heading_valid(false)
    , heading(0.0)  {
    }
  Data_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , fix_status(false)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , is_velocity_valid(false)
    , velocity(0.0)
    , is_heading_valid(false)
    , heading(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _fix_status_type;
  _fix_status_type fix_status;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef uint8_t _is_velocity_valid_type;
  _is_velocity_valid_type is_velocity_valid;

   typedef double _velocity_type;
  _velocity_type velocity;

   typedef uint8_t _is_heading_valid_type;
  _is_heading_valid_type is_heading_valid;

   typedef double _heading_type;
  _heading_type heading;





  typedef boost::shared_ptr< ::phidget_gps::Data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phidget_gps::Data_<ContainerAllocator> const> ConstPtr;

}; // struct Data_

typedef ::phidget_gps::Data_<std::allocator<void> > Data;

typedef boost::shared_ptr< ::phidget_gps::Data > DataPtr;
typedef boost::shared_ptr< ::phidget_gps::Data const> DataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phidget_gps::Data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phidget_gps::Data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace phidget_gps

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'phidget_gps': ['/home/nuccar/roscar_2018/src/roscar/phidget_gps/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::phidget_gps::Data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phidget_gps::Data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidget_gps::Data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidget_gps::Data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidget_gps::Data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidget_gps::Data_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phidget_gps::Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29c11ca0677b8b655fe476d7ca3ebb6b";
  }

  static const char* value(const ::phidget_gps::Data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29c11ca0677b8b65ULL;
  static const uint64_t static_value2 = 0x5fe476d7ca3ebb6bULL;
};

template<class ContainerAllocator>
struct DataType< ::phidget_gps::Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phidget_gps/Data";
  }

  static const char* value(const ::phidget_gps::Data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phidget_gps::Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool fix_status\n\
float64 latitude\n\
float64 longitude\n\
float64 altitude\n\
bool is_velocity_valid\n\
float64 velocity\n\
bool is_heading_valid\n\
float64 heading\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::phidget_gps::Data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phidget_gps::Data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.fix_status);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.is_velocity_valid);
      stream.next(m.velocity);
      stream.next(m.is_heading_valid);
      stream.next(m.heading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phidget_gps::Data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phidget_gps::Data_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "fix_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fix_status);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "is_velocity_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_velocity_valid);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "is_heading_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_heading_valid);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHIDGET_GPS_MESSAGE_DATA_H
