// Generated by gencpp from file maestro/MaestroIn.msg
// DO NOT EDIT!


#ifndef MAESTRO_MESSAGE_MAESTROIN_H
#define MAESTRO_MESSAGE_MAESTROIN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maestro
{
template <class ContainerAllocator>
struct MaestroIn_
{
  typedef MaestroIn_<ContainerAllocator> Type;

  MaestroIn_()
    : drive_position(0)
    , steering_position(0)  {
    }
  MaestroIn_(const ContainerAllocator& _alloc)
    : drive_position(0)
    , steering_position(0)  {
  (void)_alloc;
    }



   typedef uint16_t _drive_position_type;
  _drive_position_type drive_position;

   typedef uint16_t _steering_position_type;
  _steering_position_type steering_position;





  typedef boost::shared_ptr< ::maestro::MaestroIn_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maestro::MaestroIn_<ContainerAllocator> const> ConstPtr;

}; // struct MaestroIn_

typedef ::maestro::MaestroIn_<std::allocator<void> > MaestroIn;

typedef boost::shared_ptr< ::maestro::MaestroIn > MaestroInPtr;
typedef boost::shared_ptr< ::maestro::MaestroIn const> MaestroInConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maestro::MaestroIn_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maestro::MaestroIn_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace maestro

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'maestro': ['/home/nuccar/roscar_2018/src/roscar/maestro/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::maestro::MaestroIn_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maestro::MaestroIn_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maestro::MaestroIn_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maestro::MaestroIn_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maestro::MaestroIn_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maestro::MaestroIn_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maestro::MaestroIn_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ef4ccf9beba43d4d1391a882e59d0cf";
  }

  static const char* value(const ::maestro::MaestroIn_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ef4ccf9beba43d4ULL;
  static const uint64_t static_value2 = 0xd1391a882e59d0cfULL;
};

template<class ContainerAllocator>
struct DataType< ::maestro::MaestroIn_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maestro/MaestroIn";
  }

  static const char* value(const ::maestro::MaestroIn_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maestro::MaestroIn_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 drive_position\n\
uint16 steering_position\n\
";
  }

  static const char* value(const ::maestro::MaestroIn_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maestro::MaestroIn_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drive_position);
      stream.next(m.steering_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MaestroIn_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maestro::MaestroIn_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maestro::MaestroIn_<ContainerAllocator>& v)
  {
    s << indent << "drive_position: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.drive_position);
    s << indent << "steering_position: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.steering_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAESTRO_MESSAGE_MAESTROIN_H
