// Generated by gencpp from file maestro/MaestroOut.msg
// DO NOT EDIT!


#ifndef MAESTRO_MESSAGE_MAESTROOUT_H
#define MAESTRO_MESSAGE_MAESTROOUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maestro
{
template <class ContainerAllocator>
struct MaestroOut_
{
  typedef MaestroOut_<ContainerAllocator> Type;

  MaestroOut_()
    : error(0)
    , drive_position(0)
    , steering_position(0)
    , currTime(0.0)  {
    }
  MaestroOut_(const ContainerAllocator& _alloc)
    : error(0)
    , drive_position(0)
    , steering_position(0)
    , currTime(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _error_type;
  _error_type error;

   typedef uint16_t _drive_position_type;
  _drive_position_type drive_position;

   typedef uint16_t _steering_position_type;
  _steering_position_type steering_position;

   typedef double _currTime_type;
  _currTime_type currTime;





  typedef boost::shared_ptr< ::maestro::MaestroOut_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maestro::MaestroOut_<ContainerAllocator> const> ConstPtr;

}; // struct MaestroOut_

typedef ::maestro::MaestroOut_<std::allocator<void> > MaestroOut;

typedef boost::shared_ptr< ::maestro::MaestroOut > MaestroOutPtr;
typedef boost::shared_ptr< ::maestro::MaestroOut const> MaestroOutConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maestro::MaestroOut_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maestro::MaestroOut_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace maestro

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'maestro': ['/home/nuccar/roscar_2018/src/roscar/maestro/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::maestro::MaestroOut_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maestro::MaestroOut_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maestro::MaestroOut_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maestro::MaestroOut_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maestro::MaestroOut_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maestro::MaestroOut_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maestro::MaestroOut_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb3af52bc1b2d97529b338a827a298a4";
  }

  static const char* value(const ::maestro::MaestroOut_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb3af52bc1b2d975ULL;
  static const uint64_t static_value2 = 0x29b338a827a298a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::maestro::MaestroOut_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maestro/MaestroOut";
  }

  static const char* value(const ::maestro::MaestroOut_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maestro::MaestroOut_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 error\n\
uint16 drive_position\n\
uint16 steering_position\n\
float64 currTime\n\
";
  }

  static const char* value(const ::maestro::MaestroOut_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maestro::MaestroOut_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error);
      stream.next(m.drive_position);
      stream.next(m.steering_position);
      stream.next(m.currTime);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MaestroOut_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maestro::MaestroOut_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maestro::MaestroOut_<ContainerAllocator>& v)
  {
    s << indent << "error: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error);
    s << indent << "drive_position: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.drive_position);
    s << indent << "steering_position: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.steering_position);
    s << indent << "currTime: ";
    Printer<double>::stream(s, indent + "  ", v.currTime);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAESTRO_MESSAGE_MAESTROOUT_H
