// Generated by gencpp from file maestro/VelAndAngle.msg
// DO NOT EDIT!


#ifndef MAESTRO_MESSAGE_VELANDANGLE_H
#define MAESTRO_MESSAGE_VELANDANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maestro
{
template <class ContainerAllocator>
struct VelAndAngle_
{
  typedef VelAndAngle_<ContainerAllocator> Type;

  VelAndAngle_()
    : velocity(0.0)
    , angle(0.0)
    , currTime(0.0)  {
    }
  VelAndAngle_(const ContainerAllocator& _alloc)
    : velocity(0.0)
    , angle(0.0)
    , currTime(0.0)  {
  (void)_alloc;
    }



   typedef double _velocity_type;
  _velocity_type velocity;

   typedef double _angle_type;
  _angle_type angle;

   typedef double _currTime_type;
  _currTime_type currTime;





  typedef boost::shared_ptr< ::maestro::VelAndAngle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maestro::VelAndAngle_<ContainerAllocator> const> ConstPtr;

}; // struct VelAndAngle_

typedef ::maestro::VelAndAngle_<std::allocator<void> > VelAndAngle;

typedef boost::shared_ptr< ::maestro::VelAndAngle > VelAndAnglePtr;
typedef boost::shared_ptr< ::maestro::VelAndAngle const> VelAndAngleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maestro::VelAndAngle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maestro::VelAndAngle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace maestro

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'maestro': ['/home/nuccar/roscar_2018/src/roscar/maestro/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::maestro::VelAndAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maestro::VelAndAngle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maestro::VelAndAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maestro::VelAndAngle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maestro::VelAndAngle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maestro::VelAndAngle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maestro::VelAndAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69a8927aa7214d20fb684df692e4d5c4";
  }

  static const char* value(const ::maestro::VelAndAngle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69a8927aa7214d20ULL;
  static const uint64_t static_value2 = 0xfb684df692e4d5c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::maestro::VelAndAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maestro/VelAndAngle";
  }

  static const char* value(const ::maestro::VelAndAngle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maestro::VelAndAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 velocity\n\
float64 angle\n\
float64 currTime\n\
";
  }

  static const char* value(const ::maestro::VelAndAngle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maestro::VelAndAngle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
      stream.next(m.angle);
      stream.next(m.currTime);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelAndAngle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maestro::VelAndAngle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maestro::VelAndAngle_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "currTime: ";
    Printer<double>::stream(s, indent + "  ", v.currTime);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAESTRO_MESSAGE_VELANDANGLE_H
